var xport = require('node-xport')(module),
    mongoose = require('mongoose');

xport(mongoose.model('ModelAnime', mongoose.Schema({
    mal_id: Number,
    title: String,
    title_english: [String],
    title_synonym: [String],
    title_japanese: [String],
    poster: String,
    type: String,
    episodes: Number,
    status: String,
    aired: String,
    producers: [String],
    genres: [String],
    duration: String,
    synopsis: String,
    background: String,
    mal_rating: String,
    mal_related_sequel: [Number],
    mal_related_prequel: [Number],
    mal_related_alternative_setting: [Number],
    mal_related_alternative_version: [Number],
    mal_related_side_story: [Number],
    mal_related_parent_story: [Number],
    mal_related_summary: [Number],
    mal_related_full_story: [Number],
    mal_related_spin_off: [Number],
    mal_related_adaptation: [Number],
    mal_related_character: [Number],
    mal_related_other: [Number],
    mal_score: Number,
    mal_score_users: Number,
    mal_rank: Number,
    mal_popularity: Number,
    mal_members: Number,
    mal_favorites: Number
}, { collection: 'anime_myanimelist' })));
